name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.2'
    - name: Install dependencies
      run: stack install
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
